# Generated by Django 4.1.4 on 2022-12-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statmonitor', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('stat_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
