# Generated by Django 4.1.4 on 2022-12-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statmonitor', '0003_test'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP VIEW statement_details_view;
            CREATE OR REPLACE VIEW statement_details_view AS
            SELECT 
                a.id AS stat_id,
                a.queryid,
                a.userid,
                a.dbid,
                to_char(a.datecr, 'dd.mm.yyyy hh24:mi:ss') as datecr,
                a.calls,
                a.plans,
                to_char(a.total_exec_time / 1000::double precision, 'FM9999999990D099') AS exec_time,
                to_char(a.total_plan_time / 1000::double precision, 'FM9999999990D099') AS plan_time,
                to_char(a.total_exec_time / 1000::double precision / NULLIF(a.calls, 0)::double precision, 'FM9999999990D099') AS exec_time_per_query,
                to_char(a.total_plan_time / 1000::double precision / NULLIF(a.plans, 0)::double precision, 'FM9999999990D099') AS plan_time_per_plan,
                a.rows AS total_rows,
                a.rows / NULLIF(a.calls, 0) AS rows_per_query,
                pg_size_pretty(a.shared_blks_hit::numeric * 8192::numeric) AS cache_hit,
                pg_size_pretty(a.shared_blks_read::numeric * 8192::numeric) AS cache_miss,
                pg_size_pretty(a.shared_blks_hit / NULLIF(a.calls, 0) * 8192) AS cache_hit_per_query,
                pg_size_pretty(a.shared_blks_read / NULLIF(a.calls, 0) * 8192) AS cache_miss_per_query,
                to_char(100.0 * a.shared_blks_hit::numeric / NULLIF(a.shared_blks_hit + a.shared_blks_read, 0)::numeric, 'FM9999999990D09') AS hit_percent,
                pg_size_pretty(a.temp_blks_written::numeric * 8192::numeric) AS temp_bytes,
                pg_size_pretty(a.temp_blks_written / NULLIF(a.calls, 0) * 8192) AS temp_bytes_written_per_query
            FROM statcollector_statement_details a;
            """
        ),
    ]
