# Generated by Django 4.1.4 on 2022-12-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statmonitor', '0010_change_view7'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP VIEW IF EXISTS statement_details_view;
            CREATE VIEW statement_details_view AS 
            SELECT a.id AS stat_id,
                date_trunc('minute', a.datecr ) as query_minute,
                date_trunc('hour', a.datecr ) as query_hour,
                date_trunc('day', a.datecr ) as query_day,
                date_trunc('week', a.datecr ) as query_week,
                date_trunc('month', a.datecr ) as query_month,
                a.queryid,
                pg_roles.rolname,
                pg_database.datname,
                a.toplevel,
                to_char(a.datecr, 'dd.mm.yyyy hh24:mi:ss'::text) AS datecr,
                a.calls,
                a.plans,
                a.rows,
                round(a.total_exec_time::numeric / 1000::numeric, 3) AS total_exec_time,
                round(a.total_plan_time::numeric / 1000::numeric, 3) AS total_plan_time,
                a.shared_blks_read::numeric * 8192::numeric AS shared_blks_read_size,
                a.local_blks_read::numeric * 8192::numeric AS local_blks_read_size,
                a.temp_blks_read::numeric * 8192::numeric AS temp_blks_read_size,
                a.shared_blks_written::numeric * 8192::numeric AS shared_blks_written_size,
                a.temp_blks_written::numeric * 8192::numeric AS temp_bytes_written_size,
                a.local_blks_written::numeric * 8192::numeric AS local_blks_written_size,
                COALESCE(to_char(100.0 * a.shared_blks_hit::numeric / NULLIF(a.shared_blks_hit + a.shared_blks_read, 0)::numeric, 'FM9999999990D09'::text), ' - '::text) AS shared_blks_hit_percent,
                COALESCE(to_char(100.0 * a.local_blks_hit::numeric / NULLIF(a.local_blks_hit + a.local_blks_read, 0)::numeric, 'FM9999999990D09'::text), ' - '::text) AS local_blks_hit_percent
               FROM statcollector_statement_details a
                 JOIN pg_roles ON a.userid::oid = pg_roles.oid
                 JOIN pg_database ON a.dbid::oid = pg_database.oid
               ORDER BY                 
				a.datecr DESC;
             """
        ),
    ]
