# Generated by Django 4.1.4 on 2022-12-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statcollector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('book_ref', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('book_date', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'bookings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_no', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('passenger_id', models.CharField(max_length=20)),
                ('passenger_name', models.TextField()),
                ('contact_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tickets',
                'managed': False,
            },
        ),
        migrations.RunSQL("ALTER TABLE statcollector_queries ALTER COLUMN datecr SET DEFAULT now()"),
        migrations.RunSQL("ALTER TABLE statcollector_snapshots ALTER COLUMN datecr SET DEFAULT now()"),
        migrations.RunSQL("ALTER TABLE statcollector_statements ALTER COLUMN datecr SET DEFAULT now()"),
    ]
