# Generated by Django 4.1.4 on 2022-12-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statcollector', '0005_remove_statements_created_dbid_userid_queryid_unique_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshots',
            name='max_time',
        ),
        migrations.RemoveField(
            model_name='snapshots',
            name='mean_time',
        ),
        migrations.RemoveField(
            model_name='snapshots',
            name='min_time',
        ),
        migrations.RemoveField(
            model_name='snapshots',
            name='total_time',
        ),
        migrations.RemoveField(
            model_name='statement_details',
            name='max_time',
        ),
        migrations.RemoveField(
            model_name='statement_details',
            name='mean_time',
        ),
        migrations.RemoveField(
            model_name='statement_details',
            name='min_time',
        ),
        migrations.RemoveField(
            model_name='statement_details',
            name='total_time',
        ),
        migrations.RemoveField(
            model_name='statements',
            name='max_time',
        ),
        migrations.RemoveField(
            model_name='statements',
            name='mean_time',
        ),
        migrations.RemoveField(
            model_name='statements',
            name='min_time',
        ),
        migrations.RemoveField(
            model_name='statements',
            name='total_time',
        ),
    ]
