# Generated by Django 4.1.4 on 2022-12-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statcollector', '0006_remove_snapshots_max_time_remove_snapshots_mean_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshots',
            name='total_exec_time',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snapshots',
            name='total_plan_time',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
