# Generated by Django 4.1.4 on 2022-12-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statcollector', '0007_snapshots_total_exec_time_snapshots_total_plan_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Last_statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecr', models.DateTimeField()),
                ('userid', models.IntegerField()),
                ('dbid', models.IntegerField()),
                ('queryid', models.BigIntegerField()),
                ('toplevel', models.BooleanField(null=True)),
                ('calls', models.BigIntegerField()),
                ('plans', models.BigIntegerField()),
                ('total_plan_time', models.FloatField(null=True)),
                ('min_plan_time', models.FloatField(null=True)),
                ('max_plan_time', models.FloatField(null=True)),
                ('mean_plan_time', models.FloatField(null=True)),
                ('total_exec_time', models.FloatField(null=True)),
                ('min_exec_time', models.FloatField(null=True)),
                ('max_exec_time', models.FloatField(null=True)),
                ('mean_exec_time', models.FloatField(null=True)),
                ('rows', models.BigIntegerField()),
                ('shared_blks_hit', models.BigIntegerField()),
                ('shared_blks_read', models.BigIntegerField()),
                ('shared_blks_dirtied', models.BigIntegerField()),
                ('shared_blks_written', models.BigIntegerField()),
                ('local_blks_hit', models.BigIntegerField()),
                ('local_blks_read', models.BigIntegerField()),
                ('local_blks_dirtied', models.BigIntegerField()),
                ('local_blks_written', models.BigIntegerField()),
                ('temp_blks_read', models.BigIntegerField()),
                ('temp_blks_written', models.BigIntegerField()),
                ('blk_read_time', models.FloatField()),
                ('blk_write_time', models.FloatField()),
                ('wal_records', models.BigIntegerField(null=True)),
                ('wal_fpi', models.BigIntegerField(null=True)),
                ('wal_bytes', models.DecimalField(decimal_places=0, max_digits=18, null=True)),
            ],
            options={
                'verbose_name': 'Last_statement',
                'verbose_name_plural': 'Last_statements',
            },
        ),
        migrations.AddConstraint(
            model_name='last_statement',
            constraint=models.UniqueConstraint(fields=('dbid', 'userid', 'queryid', 'toplevel'), name='dbid_userid_queryid_toplevel_unique_1'),
        )
    ]
