# Generated by Django 4.1.4 on 2022-12-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statcollector', '0008_last_statement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last_statement',
            name='wal_bytes',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True),
        ),
        migrations.RunSQL("ALTER TABLE statcollector_last_statement ALTER COLUMN datecr SET DEFAULT now()"),
    ]
