# Generated by Django 4.1.4 on 2022-12-23 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('statcollector', '0009_alter_last_statement_wal_bytes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='last_statement',
            name='dbid_userid_queryid_toplevel_unique_1',
        ),
        migrations.RemoveField(
            model_name='last_statement',
            name='blk_read_time',
        ),
        migrations.RemoveField(
            model_name='last_statement',
            name='blk_write_time',
        ),
        migrations.RemoveField(
            model_name='last_statement',
            name='max_exec_time',
        ),
        migrations.RemoveField(
            model_name='last_statement',
            name='max_plan_time',
        ),
        migrations.RemoveField(
            model_name='last_statement',
            name='mean_exec_time',
        ),
        migrations.RemoveField(
            model_name='last_statement',
            name='mean_plan_time',
        ),
        migrations.RemoveField(
            model_name='last_statement',
            name='min_exec_time',
        ),
        migrations.RemoveField(
            model_name='last_statement',
            name='min_plan_time',
        ),
        migrations.RemoveField(
            model_name='last_statement',
            name='wal_bytes',
        ),
        migrations.RemoveField(
            model_name='last_statement',
            name='wal_fpi',
        ),
        migrations.RemoveField(
            model_name='last_statement',
            name='wal_records',
        ),
        migrations.AddField(
            model_name='last_statement',
            name='reset_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='last_statement',
            constraint=models.UniqueConstraint(fields=('dbid', 'userid', 'queryid', 'toplevel', 'reset_time'), name='dbid_userid_queryid_toplevel_unique_reset_time_unq'),
        ),
    ]
