# Generated by Django 4.1.4 on 2022-12-23 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statcollector', '0010_remove_last_statement_dbid_userid_queryid_toplevel_unique_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement_details',
            name='blk_read_time',
        ),
        migrations.RemoveField(
            model_name='statement_details',
            name='blk_write_time',
        ),
        migrations.RemoveField(
            model_name='statement_details',
            name='max_exec_time',
        ),
        migrations.RemoveField(
            model_name='statement_details',
            name='max_plan_time',
        ),
        migrations.RemoveField(
            model_name='statement_details',
            name='mean_exec_time',
        ),
        migrations.RemoveField(
            model_name='statement_details',
            name='mean_plan_time',
        ),
        migrations.RemoveField(
            model_name='statement_details',
            name='min_exec_time',
        ),
        migrations.RemoveField(
            model_name='statement_details',
            name='min_plan_time',
        ),
        migrations.RemoveField(
            model_name='statement_details',
            name='wal_bytes',
        ),
        migrations.RemoveField(
            model_name='statement_details',
            name='wal_fpi',
        ),
        migrations.RemoveField(
            model_name='statement_details',
            name='wal_records',
        ),
    ]
